version: '3.8'

services:
  ipfs:
    container_name: ipfs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/ipfs:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    network_mode: "host"
    environment:
      CHOKIDAR_USEPOLLING: "true"